chore:pr-template added
jslovers/jslovers-official-website pull request #28
Opened 2023-11-06 18:07 UTC by VenomFate-619

The template will reflected in the next coming PRs
Fixes #23

2023-11-06 18:56 UTC, Neha commented on .github/pull_request_template.md
> +## Added tests?
Add an option: updated test-cases

2023-11-06 18:57 UTC, Neha commented on .github/pull_request_template.md
> +Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
Also, add : 

snapshot of the test-cases that are passing

Steps to test the feature

2023-11-06 18:57 UTC, Neha requested changes
Thank you for the Template. This looks good. I have added 2 comments. Please check

2023-11-07 18:02 UTC, VenomFate-619 commented on .github/pull_request_template.md
> +Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
maybe in the coming future we will need to remove _snapshot of the test cases that are passing_, as there will be a CI running for a PR to test whether text cases are passing or not

2023-11-07 18:37 UTC, Neha commented on .github/pull_request_template.md
> +Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.
@VenomFate-619 Snapshot will be required even after CI as we are expecting every dev to test the test-cases passing at their local before raising a PR

2023-11-07 18:57 UTC, ekas approved these changes

2023-11-07 18:57 UTC, ekas commented
Look good to me. @Neha If you agree we could merge.

2023-11-07 19:07 UTC, Neha approved these changes

2023-11-07 19:09 UTC, ekas commented
@VenomFate-619 Thank you so much for your contribution.

2023-11-07 19:10 UTC, merged