feature: adding intial set up for cypress and e2e test case for the about page
jslovers/jslovers-official-website pull request #94
Opened 2024-06-28 16:58 UTC by saurabhsubham113

About page

# Description
Added initial setup for the cypress automation and an e2e test case for the website's **about** page.

Fixes # (issue)

**Snapshots/Videos:**

## Type of change

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [x] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert
- [ ] ✏️ Updated Test Cases

## Added tests?

- [x] 👍 Yes
- [ ] 🙅 No, because they aren't needed
- [ ] 🙋 No, because I need help

## Internationalization Support?

- [ ] 👍 Yes, Added text tokens
- [x] 🙅 No, because they aren't needed
- [ ] 🙋 No, because I need help

**Steps to test the feature:**

**Snapshot of the test-cases that are passing:**

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

2024-06-30 14:16 UTC, Neha requested changes

2024-06-30 14:16 UTC, Neha commented on cypress/support/e2e.ts
> +// Alternatively you can use CommonJS syntax:
please remove this commented code

2024-06-30 14:16 UTC, Neha commented on cypress/fixtures/example.json
> +{
Are we using these? If not, can we remove it. 
If yes, can we keep the name of the file more meaningful

2024-06-30 14:16 UTC, Neha commented on cypress.config.ts
> +    baseUrl:"http://localhost:3000",
Please create a config file and move this URL to config file and use the variable

2024-06-30 14:16 UTC, Neha commented on cypress/e2e/about.cy.ts
> +    it("about section renders correctly", () => {
it is section or page?

2024-06-30 15:33 UTC, saurabhsubham113 commented on cypress/support/e2e.ts
> +// Alternatively you can use CommonJS syntax:
sure.
i'll remove out the comments

2024-06-30 15:34 UTC, saurabhsubham113 commented on cypress/fixtures/example.json
> +{
no this is just a sample file.
i'll remove this too.

2024-06-30 15:34 UTC, saurabhsubham113 commented on cypress/e2e/about.cy.ts
> +    it("about section renders correctly", () => {
this is the about page.

2024-07-04 17:48 UTC, saurabhsubham113 commented
Hi @Neha ,

I have resolved the PR comments. Please review and any feedback is welcomed.

2024-07-17 17:09 UTC, anandaryan008 commented
Hi @Neha 

can you please let me know if this PR has been reviewed or if you have any other PR comment

2024-07-27 19:29 UTC, Neha approved these changes
thank you for your PR.

2024-07-27 19:29 UTC, merged